
package SIGView;

import SIGController.InvoiceController;
import SIGModel.HeaderSide;
import SIGModel.HeaderSideTableModel;
import SIGModel.LineSideTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Amani
 */
public class InvoiceFrame extends javax.swing.JFrame{
     public InvoiceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        headerSideTable = new javax.swing.JTable();
        headerSideTable.getSelectionModel().addListSelectionListener(listener);
        createNewInvoicebtn = new javax.swing.JButton();
        createNewInvoicebtn.addActionListener(listener);
        deleteInvoiceBtn = new javax.swing.JButton();
        deleteInvoiceBtn.addActionListener(listener);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customerNametxf = new javax.swing.JTextField();
        invoiveDatetxf = new javax.swing.JTextField();
        invoiceNumbLbl1 = new javax.swing.JLabel();
        invoiceTotalLbl1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lineSideTable = new javax.swing.JTable();
        addLineBtn = new javax.swing.JButton();
        addLineBtn.addActionListener(listener);
        deleteLineBtn = new javax.swing.JButton();
        deleteLineBtn.addActionListener(listener);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadFile = new javax.swing.JMenuItem();
        loadFile.addActionListener(listener);
        saveFile = new javax.swing.JMenuItem();
        saveFile.addActionListener(listener);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerSideTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(headerSideTable);

        createNewInvoicebtn.setText("Create New Invoice");
        createNewInvoicebtn.setActionCommand("CreateNewInvoice");

        deleteInvoiceBtn.setText("Delete Invoice");
        deleteInvoiceBtn.setActionCommand("DeleteInvoice");

        jLabel1.setText("Invoice Number");

        jLabel2.setText("Invoide Date");

        jLabel3.setText("Customer name");

        jLabel4.setText("Invoice Total");

        lineSideTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(lineSideTable);

        addLineBtn.setText("Create New Line");
        addLineBtn.setActionCommand("CreateNewLine");

        deleteLineBtn.setText("Delete Line");
        deleteLineBtn.setActionCommand("DeleteLine");

        jMenu1.setText("File");

        loadFile.setText("Load File");
        loadFile.setActionCommand("LoadFile");
        jMenu1.add(loadFile);

        saveFile.setText("Save File");
        saveFile.setActionCommand("SaveFile");
        jMenu1.add(saveFile);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(customerNametxf)
                                            .addComponent(invoiveDatetxf)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(invoiceNumbLbl1)
                                                    .addComponent(invoiceTotalLbl1))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(addLineBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteLineBtn)
                                .addGap(113, 113, 113))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(createNewInvoicebtn)
                        .addGap(87, 87, 87)
                        .addComponent(deleteInvoiceBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(invoiceNumbLbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(invoiveDatetxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(customerNametxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(invoiceTotalLbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addLineBtn)
                            .addComponent(deleteLineBtn))
                        .addGap(44, 44, 44)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteInvoiceBtn)
                    .addComponent(createNewInvoicebtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration
    private javax.swing.JButton createNewInvoicebtn;
    private javax.swing.JButton addLineBtn;
    private javax.swing.JTextField customerNametxf;
    private javax.swing.JButton deleteInvoiceBtn;
    private javax.swing.JButton deleteLineBtn;
    private javax.swing.JTextField invoiveDatetxf;
    private javax.swing.JTable lineSideTable;
    private javax.swing.JLabel invoiceNumbLbl1;
    private javax.swing.JLabel invoiceTotalLbl1;
    private javax.swing.JTable headerSideTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem loadFile;
    private javax.swing.JMenuItem saveFile;
    // End of variables declaration

    private List<HeaderSide > invList = new ArrayList<>();
    private HeaderSideTableModel  headerSideTableModel ;
    private LineSideTableModel  lineSideTableModel ;
    private HeaderDialog headerDialog;
    private LineDialog lineDialog;
    private InvoiceController listener = new InvoiceController(this);

    public InvoiceController getListener() {
        return listener;
    }

    public void setHeaderDialog(HeaderDialog headerDialog) {
        this.headerDialog = headerDialog;
    }

    public void setLineDialog(LineDialog lineDialog) {
        this.lineDialog = lineDialog;
    }

    public void setHeaderSideTableModel (HeaderSideTableModel  headerSideTableModel ) {
        this.headerSideTableModel  = headerSideTableModel ;
    }

    public void setLineSideTableModel (LineSideTableModel lineSideTableModel ) {
        this.lineSideTableModel  = lineSideTableModel ;
    }

    public JButton getcreateNewInvoicebtn() {
        return createNewInvoicebtn;
    }

    public JButton getaddLineBtn() {
        return addLineBtn;
    }

    public JTextField getcustomerNametxf() {
        return customerNametxf;
    }

    public JButton getdeleteInvoiceBtn() {
        return deleteInvoiceBtn;
    }

    public JButton getDeleteLineBtn() {
        return deleteLineBtn;
    }

    public JTextField getinvoiveDatetxf() {
        return invoiveDatetxf;
    }

    public JTable getlineSideTable() {
        return lineSideTable;
    }

    public JLabel getinvoiceNumbLbl1() {
        return invoiceNumbLbl1;
    }

    public JLabel getinvoiceTotalLbl1() {
        return invoiceTotalLbl1;
    }

    public JTable getheaderSideTable() {
        return headerSideTable;
    }

    public JMenuItem getLoadFile() {
        return loadFile;
    }

    public JMenuItem getSaveFile() {
        return saveFile;
    }

    public List<HeaderSide > getinvList() {
        return invList;
    }

    public HeaderSideTableModel  getHeaderSideTableModel () {
        return headerSideTableModel ;
    }

    public LineSideTableModel   getLineSideTableModel  () {
        return lineSideTableModel  ;
    }

    public HeaderDialog getHeaderDialog() {
        return headerDialog;
    }

    public LineDialog getLineDialog() {
        return lineDialog;
    }


}
